Laboratorio1_Estructuras2/Laboratorio1_Estructuras2/Models/Aspirante.cs
namespace Laboratorio1_Estructuras2.Models
{
    public class Aspirante : IComparable<Aspirante>
    {
        public string nombre { get; set; }
        public List<string> infoPriv { get; set; }
        public string nacimiento { get; set; }
        public string direccion { get; set; }
        public List<string> carta { get; set; } 
        public List<Dictionary<string, int>> diccionario { get; set; }
        public List<String> Convs { get; set; }
        public string reclutadores { get; set; }
        public string encriptado { get; set; }
        public int CompareTo(Aspirante other)
        {
            int result = this.infoPriv[0].CompareTo(other.infoPriv[0]);
            return result;
        }
    }
}

Laboratorio1_Estructuras2/Laboratorio1_Estructuras2/Controllers/AspiranteController.cs
using Microsoft.AspNetCore.Mvc;
using Laboratorio1_Estructuras2.Models;
using System.IO;
using System.Web;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.Text.RegularExpressions;

namespace Laboratorio1_Estructuras2.Controllers
{
    public class AspiranteController : Controller
    {
        public static AVL arbol = new AVL();
        public static List<Aspirante> listaAspi = new List<Aspirante>();
        public static List<Aspirante> listaAspi2 = new List<Aspirante>();
        public static ArbolHuffman huffman = new ArbolHuffman();
        public static ArbolIn confidencial = new ArbolIn();
        public static LZW codificador = new LZW();
        public static List<int> permu= new List<int>();
        public static Encriptacion cod = new Encriptacion();
        public static String clave = "Adelante caballero, puede pasar";
        public static RSAA Asimetrico;
        public IActionResult Index()
        {
            huffman = huffman.arbol("234987 81324QWHERTYUIOP,YUEQIUOMQKJADSF-JNVCCHU IEW9\r413278901-234567890 1 2345.ASD,FGHJKLÑHK ADSFHIOEWHE,WFHDSFJBKV-J\nVCUHA678908,793789347897 8954648798ZXCVBNMJAWFJK'ADSFJIODA  SKNLVADN,J79869");
            listaAspi.Clear();
            listaAspi2.Clear();
            permu = cod.permutacion("El_ropavejero");
            return View("Index");
        }
        [HttpPost]
        [Route("buscarNom")]
        public IActionResult encontrado(string nombre)
        {
            if (nombre == null)
            {
                return View("ErrorBuscar");
            }
            List<Aspirante> aspirantesEncontrados = new List<Aspirante>();
            aspirantesEncontrados = arbol.busqueda(nombre);
            if (aspirantesEncontrados == null)
            {
                return View("ErrorBuscar");
            }
            confidencial = new ArbolIn();
            foreach (Aspirante para in aspirantesEncontrados)
            {
                confidencial.Insertar(para);
            }
            listaAspi = confidencial.listaOrdenada();
            return View("subirDatos5", listaAspi);
        }
        public string convertidorVec(string[] vector)
        {
            string vectorAString = "";
            if (vector.Count() == 0)
            {
                return vectorAString;
            }
            for (int i = 0; i < vector.Length; i++)
            {
                if (vectorAString == "")
                {
                    vectorAString = vectorAString + vector[i];
                }
                else
                {
                    vectorAString = vectorAString + " " + vector[i];
                }
            }
            return vectorAString;
        }
        public IActionResult SubirDatos4(IFormFile archivo, string ruta)
        {
            if (archivo == null || archivo.Length == 0 || ruta == null)
            {
                ViewBag.Error = "Seleccione un archivo CSV válido. y una ruta de carpeta";
                return View("SubirDatos4", listaAspi2);
            }
            using (var reader = new StreamReader(archivo.OpenReadStream()))
            {
                if (listaAspi2.Count() > 0)
                {
                    listaAspi2.Clear();
                }
                if (confidencial.raiz != null)
                {
                    confidencial.raiz = null;
                }
                while (!reader.EndOfStream)
                {
                    var linea = reader.ReadLine();
                    var partes = linea.Split(';');
                    if (partes.Length != 2)
                    {
                        continue;
                    }
                    var instruccion = partes[0].Trim();
                    var json = partes[1].Trim();
                    try
                    {
                        JObject jsonData = JObject.Parse(json);
                        var idents = new string[3];
                        if (jsonData.TryGetValue("companies", out JToken companiesToken) && companiesToken.Type == JTokenType.Array)
                        {
                            idents = companiesToken.ToObject<string[]>();
                        }
                        string empres;
                        empres = convertidorVec(idents);
                        Aspirante aspirante = new Aspirante
                        {
                            nombre = (string)jsonData["name"],
                            infoPriv = new List<string> { (string)jsonData["dpi"] },
                            nacimiento = (string)jsonData["datebirth"],
                            direccion = (string)jsonData["address"],
                            carta = new List<string>(),
                            Convs = new List<string>(),
                            diccionario = new List<Dictionary<string, int>>(),
                            reclutadores = (string)jsonData["recluiter"]
                        };
                        aspirante.infoPriv.Add(empres);
                        switch (instruccion.ToUpper())
                        {
                            case "INSERT":
                                aspirante.infoPriv[0] = huffman.Codificar(aspirante.infoPriv[0], huffman);
                                aspirante.infoPriv[1] = huffman.Codificar(aspirante.infoPriv[1].ToUpper(), huffman);
                                aspirante.direccion = huffman.Codificar(aspirante.direccion.ToUpper(), huffman);
                                arbol.Insertar(aspirante);
                                confidencial.Insertar(aspirante);
                                break;

                            case "DELETE":
                                aspirante.infoPriv[0] = huffman.Codificar(aspirante.infoPriv[0], huffman);
                                aspirante.infoPriv[1] = huffman.Codificar(aspirante.infoPriv[1].ToUpper(), huffman);
                                aspirante.direccion = huffman.Codificar(aspirante.direccion.ToUpper(), huffman);
                                arbol.BuscaElimina(aspirante);
                                confidencial.Eliminar(aspirante);
                                break;

                            case "PATCH":
                                aspirante.infoPriv[0] = huffman.Codificar(aspirante.infoPriv[0], huffman);
                                aspirante.infoPriv[1] = huffman.Codificar(aspirante.infoPriv[1].ToUpper(), huffman);
                                aspirante.direccion = huffman.Codificar(aspirante.direccion.ToUpper(), huffman);
                                arbol.actual(aspirante);
                                confidencial.actual(aspirante);
                                break;

                            default:
                                return View("ErrorSub");
                        }
                    }
                    catch (JsonReaderException)
                    {
                        return View("ErrorSub");
                    }
                }

                try
                {
                    string[] archivos = Directory.GetFiles(ruta, "*.txt");
                    foreach (string archivoEncontrado in archivos)
                    {
                        string contenido = System.IO.File.ReadAllText(archivoEncontrado);
                        string nombreArchivo = Path.GetFileNameWithoutExtension(archivoEncontrado);
                        string[] partesNombre = nombreArchivo.Split('-');
                        if (partesNombre[0] == "REC")
                        {
                            var aspi = confidencial.Buscar(huffman.Codificar(partesNombre[1], huffman));
                            var aspirante = arbol.buscarDPI(aspi.nombre, aspi.infoPriv[0]);
                            var tupla = codificador.comprimir(huffman.Codificar(contenido.ToUpper(), huffman));
                            string codigo = tupla.Item1;
                            Dictionary<string, int> diccionario = tupla.Item2;
                            aspirante.carta.Add(codigo);
                            aspirante.diccionario.Add(diccionario);
                        }
                        else if (partesNombre[0] == "CONV")
                        {
                            var aspi = confidencial.Buscar(huffman.Codificar(partesNombre[1], huffman));
                            var aspirante = arbol.buscarDPI(aspi.nombre, aspi.infoPriv[0]);
                            string codigo = cod.permutar(contenido, permu);
                            codigo = cod.CifrarCesar(codigo);
                            aspirante.Convs.Add(codigo);
                        }
                    }
                }
                catch (Exception e)
                {
                    return View("ErrorSub");
                }
                listaAspi2 = arbol.listaOrdenada();
            }
            return RedirectToAction("SubirDatos4");
        }
        static bool EsPrimo(int numero)
        {
            if (numero <= 1)
                return false;
            if (numero <= 3)
                return true;

            if (numero % 2 == 0 || numero % 3 == 0)
                return false;

            for (int i = 5; i * i <= numero; i += 6)
            {
                if (numero % i == 0 || numero % (i + 2) == 0)
                    return false;
            }

            return true;
        }

        static int GenerarNumeroPrimoAleatorio(int min, int max)
        {
            Random random = new Random();
            List<int> primos = new List<int>();

            for (int i = min; i <= max; i++)
            {
                if (EsPrimo(i))
                    primos.Add(i);
            }

            if (primos.Count == 0)
                return -1; // No se encontraron números primos en el rango

            int indiceAleatorio = random.Next(primos.Count);
            return primos[indiceAleatorio];
        }
        [HttpPost]
        [Route("GenerarClave")]

Laboratorio1_Estructuras2/Laboratorio1_Estructuras2/Views/Aspirante/EncontradoClave.cshtml
@Model List<string>
@{
    ViewBag.Title = "Aspirantes";
}
<h2>Aspirantes encontrados</h2>
<br />
@if (Model.Count > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>nombre</th>
                <th>dpi</th>
                <th>empresas</th>
                <th>cartas</th>
                <th>conversaciones</th>
                <th>fecha de nacimiento</th>
                <th>dirección</th>
                <th>reclutadores</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model[0]</td>
                <td>@Model[1]</td> 
                <td>@Model[2]</td>
                <td>@Model[3]</td>
                <td>@Model[4]</td>
                <td>@Model[5]<td/>
                <td>@Model[6]<td/>
                <td>@Model[7]</td>
            </tr>
        </tbody>
    </table>
}
<br />
<center>
    <form method="post" action="@Url.Action("volver", "Aspirante")">
        <button type="submit" id="llamarMetodoBtn" name="llamarMetodoBtn" class="botonplano">Volver</button>
    </form>
</center>

Laboratorio1_Estructuras2/Laboratorio1_Estructuras2/Views/Aspirante/ErrorBuscar.cshtml
@{
    ViewBag.Title = "Error";
}
<h2>Error</h2>
<p>Dato no encontrado o árbol vacío, compruebe ambos casos e intente de nuevo</p>
<br />
<center>
    <form method="post" action="@Url.Action("SubirDatos4", "Aspirante")">
        <button type="submit" id="llamarMetodoBtn" name="llamarMetodoBtn" class="botonplano">Volver</button>
    </form>
</center>

Laboratorio1_Estructuras2/Laboratorio1_Estructuras2/Views/Aspirante/ErrorSub.cshtml
@{
    ViewBag.Title = "Error";
}
<h2>Error</h2>
<p>Archivo subido erróneo, verifique el archivo subido y vuelva a intentar (recuerde que es un CSV con Json en el)</p>
<br />
<center>
    <form method="post" action="@Url.Action("SubirDatos4", "Aspirante")">
        <button type="submit" id="llamarMetodoBtn" name="llamarMetodoBtn" class="botonplano">Volver</button>
    </form>
</center>

Laboratorio1_Estructuras2/Laboratorio1_Estructuras2/Views/Aspirante/ErrorSub5.cshtml
@{
    ViewBag.Title = "Error";
}
<h2>Error</h2>
<p>Compruebe que los datos enviados estén correctamente y vuelva a intentarlo</p>
<br />
<center>
    <form method="post" action="@Url.Action("volver", "Aspirante")">
        <button type="submit" id="llamarMetodoBtn" name="llamarMetodoBtn" class="botonplano">Volver</button>
    </form>
</center>

Laboratorio1_Estructuras2/Laboratorio1_Estructuras2/Views/Aspirante/Index.cshtml
<center><h1>TalentHub</h1></center>
<br />
<center><p>A continuación presentaremos nuestro proyecto de estructuras de Datos 2</p></center>
<center><p>En este programa presentaremos todos nuestros laboratorios, para comenzar pulse el botón de "Continuar"</p></center>
<br />
<center>
<form method="post" action="@Url.Action("SubirDatos4", "Aspirante")">
    <button type="submit" id="llamarMetodoBtn" name="llamarMetodoBtn" class="botonplano">Continuar</button>
    </form>
</center>

Laboratorio1_Estructuras2/Laboratorio1_Estructuras2/Views/Aspirante/SubirDatos4.cshtml
@model List<Laboratorio1_Estructuras2.Models.Aspirante>

@{
    ViewBag.Title = "Aspirantes";
}
<h2>Lista de Aspirantes</h2>

@if (ViewBag.Error != null)
{
    <div class="alert alert-danger">@ViewBag.Error</div>
}

<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="archivo">Subir archivo CSV:</label>
        <input type="file" name="archivo" id="archivo" class="form-control-file">
    </div>
    <div class="form-group">
        <label for="ruta">Ruta de carpeta:</label>
        <input type="text" name="ruta" id="ruta" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Subir archivo</button>
</form>
<br />
<div>
    <h4>Buscar:</h4>
    <center>
        <form method="post" action="@Url.Action("encontrado", "Aspirante")">
            <input type="text" id="nombre" name="nombre" placeholder="Nombre" />
            <input type="hidden" id="hiddennombre" name="nombre" value="" />
            <br />
            <button type="submit" id="llamarMetodoBtn" name="llamarMetodoBtn" class="botonplano">Buscar por nombre</button>
        </form>
    </center>
</div>
<br />

<h4>Aspirantes:</h4>
@if (Model.Count > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>nombre</th>
                <th>Datos confidenciales</th>
                <th>fecha de nacimiento</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var dato in Model)
            {
                <tr>
                    <td>@dato.nombre</td>
                    <td>@dato.infoPriv[0]</td>
                    <td>@dato.nacimiento</td>
                </tr>
            }
        </tbody>
    </table>
}
<br />
<center>
<form method="post" action="@Url.Action("index", "Aspirante")">
    <button type="submit" id="llamarMetodoBtn" name="llamarMetodoBtn" class="botonplano">volver</button>
    </form>
</center>
<script>
    $(document).ready(function () {
        $('#llamarMetodoBtn').click(function () {
            $('#hiddennombre').val($('#nombre').val());
        });
    });
</script>

Laboratorio1_Estructuras2/Laboratorio1_Estructuras2/Views/Aspirante/SubirDatos5.cshtml
@model List<Laboratorio1_Estructuras2.Models.Aspirante>

@{
    ViewBag.Title = "Aspirantes";
}
<h2>Lista de Aspirantes</h2>

@if (ViewBag.Error != null)
{
    <div class="alert alert-danger">@ViewBag.Error</div>
}

<br />
<div>
    <h4>Generar contraseña:</h4>
    <center>
        <form method="post" action="@Url.Action("generar", "Aspirante")">
            <input type="text" id="Dpi" name="Dpi" placeholder="Dpi" />
            <input type="hidden" id="hiddenDpi" name="Dpi" value="" />
            <input type="text" id="direc" name="direc" placeholder="Dirección" />
            <input type="hidden" id="hiddendirec" name="direc" value="" />
            <input type="text" id="reclu" name="reclu" placeholder="Reclutador" />
            <input type="hidden" id="hiddenreclu" name="reclu" value="" />
            <br />
            <button type="submit" id="llamarMetodoBtn" name="llamarMetodoBtn" class="botonplano">Generar Clave</button>
        </form>
    </center>
</div>
<br />
<div>
    <h4>Encontrar datos:</h4>
    <center>
        <form method="post" action="@Url.Action("buscarCla", "Aspirante")">
            <input type="text" id="Dpi1" name="Dpi1" placeholder="Dpi" />
            <input type="hidden" id="hiddenDpi1" name="Dpi1" value="" />
            <input type="text" id="reclu1" name="reclu1" placeholder="Reclutador" />
            <input type="hidden" id="hiddenreclu1" name="reclu1" value="" />
            <input type="text" id="clave1" name="clave1" placeholder="Identificador" />
            <input type="hidden" id="hiddenclave1" name="clave1" value="" />
            <input type="text" id="ident" name="ident" placeholder="Contraseña" />
            <input type="hidden" id="hiddenident" name="ident" value="" />
            <br />
            <button type="submit" id="Btn" name="Btn" class="botonplano">Mostrar datos</button>
        </form>
    </center>
</div>
<br />

<h4>Aspirantes:</h4>
@if (Model.Count > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>nombre</th>
                <th>dpi</th>
                <th>empresas</th>
                <th>cartas</th>
                <th>conversaciones</th>
                <th>fecha de nacimiento</th>
                <th>dirección</th>
                <th>reclutadores</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var dato in Model)
            {
                <tr>
                    <td>@dato.nombre</td>
                    <td>@dato.infoPriv[0]</td>
                    <td>@dato.infoPriv[1]</td>
                    <td>
                        <pre style="white-space: pre-line;">@string.Join("\n\n", dato.carta)</pre>
                    </td>
                    <td>
                        <pre style="white-space: pre-line;">@string.Join("\n\n", dato.Convs)</pre>
                    </td>
                    <td>@dato.nacimiento</td>
                    <td>@dato.direccion</td>
                    <td>@dato.reclutadores</td>
                </tr>
            }
        </tbody>
    </table>
}
<br />
<center>
<form method="post" action="@Url.Action("subirDatos4", "Aspirante")">
    <button type="submit" id="" name="" class="botonplano">volver</button>
    </form>
</center>
<script>
    $(document).ready(function () {
        $('#llamarMetodoBtn').click(function () {
            $('#hiddenDpi').val($('#Dpi').val());
            $('#hiddenreclu').val($('#reclu').val());
            $('#hiddenreclu').val($('#direc').val());
        });
    });
</script>
<script>
    $(document).ready(function () {
        $('#Btn').click(function () {
            $('#hiddenDpi1').val($('#Dpi1').val());
            $('#hiddenreclu1').val($('#reclu1').val());
            $('#hiddenclave1').val($('#clave1').val());
            $('#hiddenident').val($('#ident').val());
        });
    });
</script>

Laboratorio1_Estructuras2/Laboratorio1_Estructuras2/Views/Aspirante/clave.cshtml
@model string
<h1>Contraseña:</h1>
<br />
<h3>Sus identificadores son:</h3>
@Model
<center>
    <form method="post" action="@Url.Action("volver", "Aspirante")">
        <button type="submit" id="llamarMetodoBtn" name="llamarMetodoBtn" class="botonplano">Volver</button>
    </form>
</center>